### ISSUE TITLE
[golang] Broken setup code on `Visible Tree Node`

### ISSUE THREAD

**Issue by steveQuadros** [realAlgoMonster/contrib#24]
[Visible Tree Node](https://algo.monster/problems/visible_tree_node) has a bug in the golang setup code in the function `buildTree` where it increments `*pos` then checks the value of the incremented pointer (which could be 'x', causing a error in `strconv.Atoi` that was swallowed). Below is code that fixes the incremented pointer (using the value fetched before incrementing, and also panic, so that future users won't have to dig into the setup code if there is some future error.

```golang
func buildTree(nodes []string, pos *int) *Node {
    val := nodes[*pos]
    *pos++
    if val == "x" {
        return nil
    }
    v, err := strconv.Atoi(val)
    left := buildTree(nodes, pos)
    right := buildTree(nodes, pos)
    if err != nil {
        panic("err converting to int: " + err.Error())    
    }
    return &Node{v, left, right}
}
```

**Comment by lzjluzijie** [comment]
Thank you for pointing out! This is now fixed.
